CREATE TABLE sponsors (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  logoUrl TEXT NOT NULL,
  link VARCHAR(2048) NOT NULL,
  createdByUserId INT NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (createdByUserId) REFERENCES users(id) ON DELETE RESTRICT
);
